### ISSUE TITLE
cannot import main from pip

### ISSUE THREAD

**Issue by jugmac00** [deadsnakes/issues#101]
### description

tox does not work with python 3.9

```
Products.ZopeTree on  py3 [!] via 🐍 v3.6.8 (tox-py36) 
❯ tox -e=py39
GLOB sdist-make: /home/jugmac00/Projects/Products.ZopeTree/setup.py
py39 create: /home/jugmac00/Projects/Products.ZopeTree/.tox/py39
ERROR: invocation failed (exit code 1), logfile: /home/jugmac00/Projects/Products.ZopeTree/.tox/py39/log/py39-0.log
====================================================================================== log start ======================================================================================
Already using interpreter /usr/bin/python3.9
Using base prefix '/usr'
New python executable in /home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python3.9
Also creating executable in /home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python
Command /home/jugmac00/Proje...x/py39/bin/python3.9 -m pip config list had error code 1
Installing setuptools, pip, wheel...

  Complete output from command /home/jugmac00/Proje...x/py39/bin/python3.9 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/commands/__init__.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/commands/completion.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 25, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/index.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_vendor/html5lib/__init__.py", line 25, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_vendor/html5lib/html5parser.py", line 8, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_vendor/html5lib/_tokenizer.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_vendor/html5lib/_trie/__init__.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_vendor/html5lib/_trie/py.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_vendor/html5lib/_trie/_base.py", line 3, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
ImportError: cannot import name 'main' from 'pip' (/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/__init__.py)
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv.py", line 2628, in <module>
    main()
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv.py", line 860, in main
    create_environment(
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/home/jugmac00/Virtualenvironments/tox-py36/lib/python3.6/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /home/jugmac00/Proje...x/py39/bin/python3.9 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /usr/bin/python3.9

======================================================================================= log end =======================================================================================
ERROR: InvocationError for command /home/jugmac00/Virtualenvironments/tox-py36/bin/python3.6 -m virtualenv --no-download --python /usr/bin/python3.9 py39 (exited with code 1)
_______________________________________________________________________________________ summary _______________________________________________________________________________________
ERROR:   py39: InvocationError for command /home/jugmac00/Virtualenvironments/tox-py36/bin/python3.6 -m virtualenv --no-download --python /usr/bin/python3.9 py39 (exited with code 1)


```

#### lsb_release -a

```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

```

#### uname -a

```
❯ uname -a
Linux jugmac00-XPS-13-9370 4.15.0-1059-oem #68-Ubuntu SMP Sat Oct 12 04:02:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

tried to use different instances of tox, via pipx, via python3.6, python3.8... no luck

Any hint for me?

I was soooo close :-)
https://twitter.com/jugmac00/status/1197564802618580992

**Comment by asottile** [comment]
yeah this is unfortunately using the `pip` / `pkg-resources` wheels that ship with the operating system -- I'd suggest using a `virtualenv` or `get-pip.py` to make that work better

Unfortunately, `virtualenv` isn't quite ready for python3.9 yet -- but we're working on that here: https://github.com/pypa/virtualenv/pull/1450

**Comment by asottile** [comment]
this is the other issue to follow: https://github.com/pypa/virtualenv/issues/1449

**Comment by jugmac00** [comment]
Thank you so much for always taking the time to really explain what is going on!

**Comment by asottile** [comment]
no problem! happy to help

**Comment by bskinn** [comment]
virtualenv 16.7.8 is released with a fix -- it should work ok now with Python 3.9

**Comment by jugmac00** [comment]
Thanks Brian!

Actually, I am not sure how this all works together, but as I installed python3.9-venv from the deadsnake ppa I guess I should wait until it gets an update.

The py39 venv built by tox is broken, so there isn't even the pip module with which I could update virtualenv...

```
.tox/py39/bin/python3.9 -m pip
/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python3.9: No module named pip
```

So, I guess I am missing the big picture, but I am sure it will work all once the ppa gets updated - and actually testing with py39 would have been nice, but it is not very urgent.

**Comment by bskinn** [comment]
Ahh, yeah, the deadsnakes python3.9 has a really old pip, currently.  That's fixed easily enough [using `get-pip.py`](https://github.com/bskinn/azure-pipelines-template/blob/patch-1/run-tox-env.yml#L101-L102) directly on the ppa-installed python3.9.

Then the best strategy is probably to `python3.9 -m pip install virtualenv` -- that should get you v16.7.8, with the new fix.

If there are still problems after that... yeah, then I'm tapped out.  |-[]

**Comment by asottile** [comment]
technically, deadsnakes doesn't even ship pip :) -- the ubuntu pip is the old one

**Comment by bskinn** [comment]
Aha, so it's not even invoking the right Python version! No wonder. 

Would it make sense to prepare a deadsnakes `python39-pip` package?

**Comment by asottile** [comment]
I don't really know how such a package would work 🤔 -- it'd be very hard not to clobber the system pip in any reasonable way (unless it was only exposed as `pip-3.9` or something of the sort)

**Comment by jugmac00** [comment]
@asottile Sorry for bothering you once more.

I now know how to workaround the problem, but ...

Can you fix this problem by creating a new package for python3.9-venv? And will you do it?

**Comment by asottile** [comment]
the `python3.9-venv` package works fine -- it includes modern pip wheels.

```console
$ python3.9 -m venv venv39
$ venv39/bin/pip install astpretty
Collecting astpretty
  Downloading https://files.pythonhosted.org/packages/3f/c2/1791d5945767ead406c6bb0fda1f482106dcc0ba370819bcc79512ba1260/astpretty-1.7.0-py2.py3-none-any.whl
Installing collected packages: astpretty
Successfully installed astpretty-1.7.0
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ ./venv39/bin/python --version
Python 3.9.0a1
```

what's not working is using system `pip`, which (in debian world) isn't even really a supported path.  debian assumes that you use the package manager (`apt`) to manage system packages

but for that all you need is to install a modern version of `virtualenv` or `pip` at your system and you should be good to go (either with `get-pip.py`, etc.)
