### ISSUE TITLE
urllib.error.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by henrik242** [deadsnakes/issues#111]
I have installed python 3.7 using the following on Ubuntu Trusty:

    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:deadsnakes
    sudo apt-get update
    sudo apt-get install -y python3.7
    sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 10

And I'm running this script:

```
#!/usr/bin/env python3

import urllib.request


def do_http(url):
    req = urllib.request.Request(url)
    response = urllib.request.urlopen(req)
    content = response.read()
    code = response.code
    response.close()
    print(code)
    print(content)


if __name__ == '__main__':
    do_http("https://synth.no")
```

And this results in:
```
Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    do_http("https://synth.no")
  File "./test.py", line 8, in do_http
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 548, in _open
    'unknown_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

**Comment by henrik242** [comment]
Probably because of https://github.com/deadsnakes/issues/issues/63 ? Bummer...

**Comment by asottile** [comment]
yep, and there's officially nothing we can do about it now that trusty is end-of-lifed and frozen
