### ISSUE TITLE
Cannot "import ssl" because "libpython3.7-minimal" is missing the "_ssl.cpython-37m-x86_64-linux-gnu.so" library on Ubuntu LTS Trusty 64bits (14.04)

### ISSUE THREAD

**Issue by sebma** [deadsnakes/issues#134]
### description
Cannot `import ssl` with python3.7 : 
```python
$ /usr/bin/python3.7 -c "import ssl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
$ dpkg -S python3.7/ssl.py
libpython3.7-minimal:amd64: /usr/lib/python3.7/ssl.py
$ apt-cache policy libpython3.7-minimal
python3.7:
  Installed: 3.7.0-1+trusty1
  Candidate: 3.7.0-1+trusty1
  Version table:
 *** 3.7.0-1+trusty1 0
        500 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
$ dpkg -L libpython3.7-minimal | grep ssl.*so$
$

```
### os information
Linux Ubuntu 14.04.6 LTS 64bits

#### lsb_release -a

```
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
```

#### uname -a

```
Linux seb-C70D-B-311 4.4.0-148-generic #174~14.04.1-Ubuntu SMP Thu May 9 08:17:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
duple #63
