### ISSUE TITLE
Can't create virtualenv with 3.9

### ISSUE THREAD

**Issue by zgoda** [deadsnakes/issues#137]
### description

Command `/usr/bin/python3.9 -m venv venv` fails to create virtual environment.

```
$ /usr/bin/python3.9 -m venv venv
Error: Command '['/home/jazg/work/pl_fts/venv/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

$ venv/bin/python3.9 -Im ensurepip --upgrade --default-pip
Looking in links: /tmp/tmpqjnm05kg
Processing /tmp/tmpqjnm05kg/setuptools-49.2.1-py3-none-any.whl
Processing /tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 397, in run
    installed = install_given_reqs(
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/req/req_install.py", line 779, in install
    scheme = get_scheme(
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/locations.py", line 185, in get_scheme
    scheme = distutils_scheme(
  File "/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl/pip/_internal/locations.py", line 125, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.9/distutils/command/install.py", line 306, in finalize_options
    (prefix, exec_prefix) = get_config_vars('prefix', 'exec_prefix')
  File "/usr/lib/python3.9/distutils/sysconfig.py", line 512, in get_config_vars
    func()
  File "/usr/lib/python3.9/distutils/sysconfig.py", line 472, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__x86_64-linux-gnu'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/lib/python3.9/ensurepip/__init__.py", line 210, in _main
    return _bootstrap(
  File "/usr/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/usr/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jazg/work/pl_fts/venv/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpqjnm05kg/setuptools-49.2.1-py3-none-any.whl\', \'/tmp/tmpqjnm05kg/pip-20.2.3-py2.py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpqjnm05kg\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 2.
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

#### uname -a

```
Linux PL006947 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I see [someone had the same issue](https://stackoverflow.com/questions/59439725/cant-create-virtualenv-on-ubuntu-18-04-with-python-3-8#comment113610467_59793251).

**Comment by asottile** [comment]
can confirm, looks like the name of this module changed with debian, it is `_sysconfigdata__linux_x86_64-linux-gnu` -- will have to adjust the debian patches to fix that

thanks for the report!

**Comment by asottile** [comment]
wow I'm saddened / surprised the many people on stackoverflow didn't report this sooner :/

**Comment by asottile** [comment]
thanks for the report -- I've fixed this in https://github.com/deadsnakes/python3.9 -- it should be available within the hour

tracked down why 3.8 was broken, it looks like I fixed that already 👍
