### ISSUE TITLE
AttributeError: module 'ast' has no attribute 'NodeVisitor'

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [deadsnakes/issues#192]
### description
I have installed Python 3.10 from this PPA, upon executing the `python3.10` command, the following message is printed

```
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 463, in register_readline
    import rlcompleter
  File "/usr/lib/python3.10/rlcompleter.py", line 34, in <module>
    import inspect
  File "/usr/lib/python3.10/inspect.py", line 901, in <module>
    class _ClassFinder(ast.NodeVisitor):
AttributeError: module 'ast' has no attribute 'NodeVisitor'
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

#### uname -a

```
Linux Ubuntu-LilyWhite 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Ravenclaw-OIer** [comment]
Indeed. I'm writing a interpreter for a toy language at the moment and I (unwittingly) chose ast.py as the filename.

But why doesn't the Python 3.8 that came out of the box complain about this?

**Comment by asottile** [comment]
because python3.8's inspect.py does not access attributes on the `ast` module at module scope
