### ISSUE TITLE
Unable to install any Python 3.11 or 3.10 packages via pip

### ISSUE THREAD

**Issue by rjc** [deadsnakes/issues#215]
### description

Unable to install any package via pip on Python 3.10 and 3.11.

Python 3.11:

```
$ python3.11 -m pip install --user pip-install-test
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)
```

Python 3.10:

```
$ python3.10 -m pip install --user pip-install-test
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)
```

For reference, Python 3.9:

```
$ python3.9 -m pip install --user pip-install-test
Collecting pip-install-test
  Downloading pip_install_test-0.5-py3-none-any.whl (1.7 kB)
Installing collected packages: pip-install-test
Successfully installed pip-install-test-0.5
```

#### lsb_release -a

```
LSB Version:    core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

#### uname -a

```
Linux euclid 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
yeah system pip on focal is just too old, nothing I can do about that

I would strongly suggest **never using system pip** anyway -- it's a one way ticket to breaking your system: https://youtu.be/O390_abzo08

**Comment by rjc** [comment]
> I would strongly suggest **never using system pip** anyway -- it's a one way ticket to breaking your system: https://youtu.be/O390_abzo08

Right, I thought that Python 3.11 using system pip **is** the bug. I was under the impression that installing `python3.11-full` will make sure that Python 3.11 does **not** use the system pip but its own bundled pip. I could have sworn you used to provide _python3.x-pip_ packages but I guess I must have got it muddled-up with _python3.x-venv_ ones. Sure enough:

```
$ python3.9 -m pip -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)
$ python3.10 -m pip -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
$ python3.11 -m pip -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.11)
```

I worked around the issue with `ensurepip`:

```
$ python3.11 -m ensurepip --user --upgrade    
Looking in links: /tmp/tmp2vm4hxu7
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (45.2.0)
Processing /tmp/tmp2vm4hxu7/setuptools-58.1.0-py3-none-any.whl
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.0.2)
Processing /tmp/tmp2vm4hxu7/pip-22.0.4-py3-none-any.whl
Installing collected packages: setuptools, pip
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
Successfully installed pip-22.0.4 setuptools-58.1.0
$ python3.11 -m pip install --user pip-install-test
Collecting pip-install-test
  Using cached pip_install_test-0.5-py3-none-any.whl (1.7 kB)
Installing collected packages: pip-install-test
Successfully installed pip-install-test-0.5
$ python3.11 -m pip -V
pip 22.0.4 from /u/r/rjc/.local/lib/python3.11/site-packages/pip (python 3.11)
```

Either way, is there any chance you can bundle pip with each Python version or simply provide a vendored(?) package, i.e. _python3.9-pip_, _python3.10-pip_, python3.11-pip_ etc.

BTW, I never use install anything system-wide and/or as root, and only ever use with `--user`.

> in the future, please search the issue tracker

I did - simply thought it's a **new** bug.

**Comment by asottile** [comment]
ensurepip **creates a system pip** -- you're missing the point -- you don't want that

**Comment by rjc** [comment]
> ensurepip **creates a system pip** -- you're missing the point -- you don't want that

As per above:

> BTW, I never install anything system-wide and/or as root, and only ever use pip with --user.

So no, all good here:

```
$ python3.11 -m ensurepip --user --upgrade
$ python3.11 -m pip -V
pip 22.0.4 from /u/r/rjc/.local/lib/python3.11/site-packages/pip (python 3.11)
```
 :^)

**Comment by asottile** [comment]
no there is not, that would be handing the user a footgun
