### ISSUE TITLE
pleasse add package python3.10-pip working

### ISSUE THREAD

**Issue by amidevous** [deadsnakes/issues#219]
pleasse add package python3.10-pip

for ubuntu 18.04, 20.04 and 22.04

pip3 return pip of 3.6 or 3.8

pip3.10 not found

install ussing bash script not work

curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

Keyring is skipped due to an exception: module 'collections' has no attribute 'MutableMapping'
Collecting pip
  Using cached pip-22.1.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.1.1
    Uninstalling pip-22.1.1:
      Successfully uninstalled pip-22.1.1
Successfully installed pip-22.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

python3.10 -m pip install bs4
Keyring is skipped due to an exception: module 'collections' has no attribute 'MutableMapping'
Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 12, in <module>
          import setuptools.version
        File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
          __import__('pkg_resources.extern.packaging.requirements')
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
          from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
        File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
          __import__(extant)
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
          collections.MutableMapping.register(ParseResults)
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

ok solve problem

python3.10 -m ensurepip --upgrade

but it would still be much easier if pip was present on the ppa as is the case for the official versions

official version package python-pip and python3-pip

ppa package

python3.7-pip

working to

pip3.7

python3.8-pip

working to

pip3.8

python3.9-pip

working to

pip3.9

python3.10-pip

working to

pip3.10

python3.11-pip

working to

pip3.11

etc

**Comment by asottile** [comment]
there's no such package and using global pip is usually a bad idea anyway 

I'd recommend a virtualenv

but if you want to, deadsnakes provides ensurepip or you can use get-pip

in the future please search the tracker, there are many many duplicates
