### ISSUE TITLE
python3.7 on Ubuntu22.04 error  cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)

### ISSUE THREAD

**Issue by mattjwarren** [deadsnakes/issues#222]
### description
python3.7 installed from deadsnakes PPA into Ubuntu22.04 with
sudo apt install python3.7

After installing python3.7 for ubuntu22.04 I have the problem;

root@ubuntu-1:/# python3.7
Python 3.7.13 (default, Apr 24 2022, 01:06:43)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)

Using the system python, 3.10 this import is succesful.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

#### uname -a

```
Linux ubuntu-1 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mattjwarren** [comment]
This may be a red herring, but some googling suggested I try 

root# python3.7 -m pip install pycairo
Requirement already satisfied: pycairo in /usr/lib/python3/dist-packages (1.20.1)
root# python3.7 -m pip install PyGObject
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (3.42.0)
Requirement already satisfied: pycairo>=1.16.0 in /usr/lib/python3/dist-packages (from PyGObject) (1.20.1)


This appears that even though I am calling python3.7 -m pip install ....
It is being satisfied with packages installed in dist-packages, where I understood that should only be valid for the system python python3.10 ?

so  python3.7 import gi  is attempting to import compiled c modules from the system pythons installation, which would likely fail as they are from a python3.10 compilation?

**Comment by mattjwarren** [comment]
I am relying on python3.7 because the project requires tensorflow 1.15 which is not supported in python above 3.7
