### ISSUE TITLE
Cannot add ppa:deadsnakes on debian bookworm

### ISSUE THREAD

**Issue by Neah-Ko** [deadsnakes/issues#271]
### description

_fill in a description of your issue -- be specific!_

I get the following output upon trying to add the ppa

```bash
$ sudo add-apt-repository ppa:deadsnakes
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
```

The ppa object representation seems to be missing an 'lp' property.

### os information

```
python --version
Python 3.11.2
```
```
$ pip freeze
arandr==0.1.11
asn1crypto==1.5.1
attrs==22.2.0
blinker==1.5
Brlapi==0.8.4
certifi==2022.9.24
chardet==5.1.0
charset-normalizer==3.0.1
cryptography==38.0.4
cupshelpers==1.0
dbus-python==1.3.2
distro==1.8.0
distro-info==1.5+deb12u1
docker==5.0.3
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
gyp==0.1
html5lib==1.1
httplib2==0.20.4
idna==3.3
jsonpointer==2.3
jsonschema==4.10.3
lazr.restfulclient==0.14.5
lazr.uri==1.0.6
louis==3.24.0
Mako==1.2.4.dev0
MarkupSafe==2.1.2
mechanize==0.4.8
netifaces==0.11.0
oauthlib==3.2.2
pycairo==1.20.1
pycups==2.0.1
pycurl==7.45.2
PyGObject==3.42.2
PyJWT==2.6.0
pyparsing==3.0.9
pyrsistent==0.18.1
PySimpleSOAP==1.16.2
pysmbc==1.0.23
python-apt==2.6.0
python-dateutil==2.8.2
python-debian==0.1.49
python-debianbts==4.0.1
python-dotenv==0.21.0
pyxdg==0.28
PyYAML==6.0
ranger-fm==1.9.3
reportbug==12.0.0
requests==2.28.1
rfc3987==1.3.8
six==1.16.0
texttable==1.6.7
uritemplate==4.1.1
urllib3==1.26.12
wadllib==1.3.6
webcolors==1.11.1
webencodings==0.5.1
websocket-client==1.2.3
xdg==5
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

#### uname -a

```bash
Linux debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

**Comment by bensnhunt** [comment]
Hey @Neah-Ko did you get this resolved?

**Comment by asottile** [comment]
no they did not.  it is not supported
