### ISSUE TITLE
HTTP Error 503: Service Unavailable 

### ISSUE THREAD

**Issue by japineda3** [deadsnakes/issues#279]
Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-94-generic x86_64)
 
I execute : sudo add-apt-repository ppa:deadsnakes/ppa -y

And I get this error:
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 347, in main
    shortcut = handler(source, **shortcut_params)
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in _init_
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
    self._lpteam = self.lp.people(self.teamname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
    self.lp = login_func("%s.%s" % (self.module, self.class.name_),
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
    return cls(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in _init_
    super(Launchpad, self)._init_(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in _init_
    self._wadl = self._browser.get_wadl_application(self._root_uri)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 503: Service Unavailable
Response headers:
—
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
connection: close
content-length: 14113
content-type: text/html; charset=UTF-8
expires: Thu, 01 Jan 1970 00:00:00 GMT
p3p: CP="CAO PSA OUR"
pragma: no-cache
status: 503

Any help? Thanks.

**Comment by asottile** [comment]
that's either a proxy your work has or launchpad being down we cannot help with either
